# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'diseño_proyecto_QTDesigner.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1600, 1000)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.superior = QtWidgets.QFrame(self.centralwidget)
        self.superior.setStyleSheet("background-color: black")
        self.superior.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.superior.setFrameShadow(QtWidgets.QFrame.Raised)
        self.superior.setObjectName("superior")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.superior)
        self.horizontalLayout.setContentsMargins(0, 7, 0, 12)
        self.horizontalLayout.setSpacing(16)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_menu = QtWidgets.QPushButton(self.superior)
        self.btn_menu.setMinimumSize(QtCore.QSize(200, 0))
        self.btn_menu.setStyleSheet("QPushButton{\n"
"font: 87 12pt \"Cascadia Code SemiBold\";\n"
"color: white;\n"
"background-color: black;\n"
"border-radius: 0px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgb(185, 185, 185);\n"
"font: 87 12pt \"Cascadia Code SemiBold\";\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(166, 166, 166);\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Iconos de Botones/icons8-menú-64.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_menu.setIcon(icon)
        self.btn_menu.setIconSize(QtCore.QSize(40, 40))
        self.btn_menu.setObjectName("btn_menu")
        self.horizontalLayout.addWidget(self.btn_menu)
        spacerItem = QtWidgets.QSpacerItem(1089, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btn_minimizar = QtWidgets.QPushButton(self.superior)
        self.btn_minimizar.setStyleSheet("QPushButton{\n"
"border:0px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(185, 185, 185);\n"
"}")
        self.btn_minimizar.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Iconos de Botones/icons8-minimizar-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_minimizar.setIcon(icon1)
        self.btn_minimizar.setIconSize(QtCore.QSize(40, 40))
        self.btn_minimizar.setObjectName("btn_minimizar")
        self.horizontalLayout.addWidget(self.btn_minimizar)
        self.btn_maximizar = QtWidgets.QPushButton(self.superior)
        self.btn_maximizar.setStyleSheet("QPushButton {\n"
"border: 0px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(185, 185, 185);\n"
"}")
        self.btn_maximizar.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Iconos de Botones/icons8-imagen-completa-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_maximizar.setIcon(icon2)
        self.btn_maximizar.setIconSize(QtCore.QSize(40, 40))
        self.btn_maximizar.setObjectName("btn_maximizar")
        self.horizontalLayout.addWidget(self.btn_maximizar)
        self.btn_restaurar = QtWidgets.QPushButton(self.superior)
        self.btn_restaurar.setStyleSheet("QPushButton {\n"
"border: 0px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(185, 185, 185);\n"
"}")
        self.btn_restaurar.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Iconos de Botones/icons8-pantalla-completa-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_restaurar.setIcon(icon3)
        self.btn_restaurar.setIconSize(QtCore.QSize(40, 40))
        self.btn_restaurar.setObjectName("btn_restaurar")
        self.horizontalLayout.addWidget(self.btn_restaurar)
        self.btn_salir = QtWidgets.QPushButton(self.superior)
        self.btn_salir.setStyleSheet("QPushButton {\n"
"border: 0px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: red;\n"
"}")
        self.btn_salir.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("Iconos de Botones/icons8-cerrar-ventana-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_salir.setIcon(icon4)
        self.btn_salir.setIconSize(QtCore.QSize(40, 40))
        self.btn_salir.setObjectName("btn_salir")
        self.horizontalLayout.addWidget(self.btn_salir)
        self.verticalLayout.addWidget(self.superior)
        self.inferior = QtWidgets.QFrame(self.centralwidget)
        self.inferior.setStyleSheet("background-color: white")
        self.inferior.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.inferior.setFrameShadow(QtWidgets.QFrame.Raised)
        self.inferior.setObjectName("inferior")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.inferior)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.menu = QtWidgets.QFrame(self.inferior)
        self.menu.setMinimumSize(QtCore.QSize(0, 0))
        self.menu.setMaximumSize(QtCore.QSize(0, 16777215))
        self.menu.setBaseSize(QtCore.QSize(0, 0))
        self.menu.setStyleSheet("QFrame{\n"
"background-color: rgb(142, 31, 76);\n"
"}\n"
"\n"
"QPushButton{\n"
"text-align:left;\n"
"background-color: rgb(142, 31, 76);\n"
"color: white;\n"
"border-top-left-radius: 20px;\n"
"border-bottom-left-radius: 20px;\n"
"\n"
"font: 75 12pt \"Cascadia Code SemiBold\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"border-bottom-left-radius: 20px;\n"
"border-top-left-radius: 20px;\n"
"color: black;\n"
"background-color: rgb(167, 167, 167);\n"
"\n"
"\n"
"font: 75 12pt \"Cascadia Code SemiBold\";\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: #b6b6b6\n"
"}\n"
"")
        self.menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menu.setObjectName("menu")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.menu)
        self.horizontalLayout_9.setContentsMargins(40, 20, 40, 20)
        self.horizontalLayout_9.setSpacing(4)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem1)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setContentsMargins(50, 0, -1, -1)
        self.verticalLayout_9.setSpacing(100)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.btn_inicio = QtWidgets.QPushButton(self.menu)
        self.btn_inicio.setMaximumSize(QtCore.QSize(300, 40))
        self.btn_inicio.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code SemiBold")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(9)
        font.setStrikeOut(False)
        self.btn_inicio.setFont(font)
        self.btn_inicio.setStyleSheet("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("Iconos de Botones/icons8-casa-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_inicio.setIcon(icon5)
        self.btn_inicio.setIconSize(QtCore.QSize(25, 25))
        self.btn_inicio.setObjectName("btn_inicio")
        self.verticalLayout_9.addWidget(self.btn_inicio, 0, QtCore.Qt.AlignLeft)
        self.btn_calculadora = QtWidgets.QPushButton(self.menu)
        self.btn_calculadora.setMinimumSize(QtCore.QSize(0, 0))
        self.btn_calculadora.setMaximumSize(QtCore.QSize(300, 40))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("Iconos de Botones/icons8-calculadora-64.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_calculadora.setIcon(icon6)
        self.btn_calculadora.setIconSize(QtCore.QSize(25, 25))
        self.btn_calculadora.setObjectName("btn_calculadora")
        self.verticalLayout_9.addWidget(self.btn_calculadora, 0, QtCore.Qt.AlignLeft)
        self.btn_sistema_dinamico = QtWidgets.QPushButton(self.menu)
        self.btn_sistema_dinamico.setMaximumSize(QtCore.QSize(300, 40))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("Iconos de Botones/icons8-dinámica-negativa-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_sistema_dinamico.setIcon(icon7)
        self.btn_sistema_dinamico.setIconSize(QtCore.QSize(25, 25))
        self.btn_sistema_dinamico.setObjectName("btn_sistema_dinamico")
        self.verticalLayout_9.addWidget(self.btn_sistema_dinamico, 0, QtCore.Qt.AlignLeft)
        self.horizontalLayout_9.addLayout(self.verticalLayout_9)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem2)
        self.horizontalLayout_2.addWidget(self.menu)
        self.contenedor = QtWidgets.QFrame(self.inferior)
        self.contenedor.setStyleSheet("background-color: white")
        self.contenedor.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.contenedor.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contenedor.setObjectName("contenedor")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.contenedor)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.cambiarPagina = QtWidgets.QStackedWidget(self.contenedor)
        self.cambiarPagina.setObjectName("cambiarPagina")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.page)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame = QtWidgets.QFrame(self.page)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 34)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_8 = QtWidgets.QFrame(self.frame)
        self.frame_8.setStyleSheet("QLabel{\n"
"font: 50 16pt  \"Pacifico\"\n"
"}")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_2.setSpacing(15)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.frame_8)
        self.label_3.setStyleSheet("font: 50 40pt \"Cascadia SemiBold\";")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3, 0, QtCore.Qt.AlignHCenter)
        self.label_4 = QtWidgets.QLabel(self.frame_8)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_3.addWidget(self.frame_8)
        self.imagen_cutonala = QtWidgets.QLabel(self.frame)
        self.imagen_cutonala.setMinimumSize(QtCore.QSize(326, 155))
        self.imagen_cutonala.setSizeIncrement(QtCore.QSize(200, 200))
        self.imagen_cutonala.setText("")
        self.imagen_cutonala.setPixmap(QtGui.QPixmap("../../../Downloads/Simbolo Cutonala.jpeg"))
        self.imagen_cutonala.setScaledContents(False)
        self.imagen_cutonala.setAlignment(QtCore.Qt.AlignCenter)
        self.imagen_cutonala.setWordWrap(False)
        self.imagen_cutonala.setOpenExternalLinks(False)
        self.imagen_cutonala.setObjectName("imagen_cutonala")
        self.verticalLayout_3.addWidget(self.imagen_cutonala)
        self.verticalLayout_3.setStretch(0, 1)
        self.verticalLayout_3.setStretch(1, 5)
        self.horizontalLayout_5.addWidget(self.frame)
        self.cambiarPagina.addWidget(self.page)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.page_4)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.frame_9 = QtWidgets.QFrame(self.page_4)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.frame_10 = QtWidgets.QFrame(self.frame_9)
        self.frame_10.setStyleSheet("\n"
"QFrame{\n"
"background-color: white;\n"
"}\n"
"QLabel{\n"
"color: white;\n"
"font: 87 12pt \"Arial Black\";\n"
"}\n"
"QPlainTextEdit{\n"
"font: 63 12pt \"Cascadia Code PL SemiBold\";\n"
"}")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.frame_12 = QtWidgets.QFrame(self.frame_10)
        self.frame_12.setMaximumSize(QtCore.QSize(16777215, 300))
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_12)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.verticalFrame = QtWidgets.QFrame(self.frame_12)
        self.verticalFrame.setMaximumSize(QtCore.QSize(16777215, 342342))
        self.verticalFrame.setStyleSheet("border: 0px;\n"
"background-color: rgb(255, 184, 112); ")
        self.verticalFrame.setObjectName("verticalFrame")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.verticalFrame)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.enlace = QtWidgets.QLabel(self.verticalFrame)
        self.enlace.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.enlace.setStyleSheet("color: white;")
        self.enlace.setOpenExternalLinks(True)
        self.enlace.setObjectName("enlace")
        self.verticalLayout_12.addWidget(self.enlace)
        self.horizontalLayout_11.addWidget(self.verticalFrame)
        self.verticalLayout_11.addWidget(self.frame_12)
        self.verticalLayout_11.setStretch(0, 7)
        self.verticalLayout_10.addWidget(self.frame_10)
        self.frame_11 = QtWidgets.QFrame(self.frame_9)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_11)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.frame_13 = QtWidgets.QFrame(self.frame_11)
        self.frame_13.setStyleSheet("font: 50 10pt \"Cascadia SemiBold\";")
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_13)
        self.verticalLayout_13.setContentsMargins(0, 22, 0, 0)
        self.verticalLayout_13.setSpacing(4)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_7 = QtWidgets.QLabel(self.frame_13)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_13.addWidget(self.label_7)
        self.tabla_probabilidades_buhos = QtWidgets.QTableWidget(self.frame_13)
        self.tabla_probabilidades_buhos.setMinimumSize(QtCore.QSize(0, 0))
        self.tabla_probabilidades_buhos.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tabla_probabilidades_buhos.setStyleSheet("QTableWidget::item {text-align: center;}")
        self.tabla_probabilidades_buhos.setAlternatingRowColors(False)
        self.tabla_probabilidades_buhos.setRowCount(3)
        self.tabla_probabilidades_buhos.setObjectName("tabla_probabilidades_buhos")
        self.tabla_probabilidades_buhos.setColumnCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_probabilidades_buhos.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_probabilidades_buhos.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_probabilidades_buhos.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignTop)
        self.tabla_probabilidades_buhos.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_probabilidades_buhos.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_probabilidades_buhos.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tabla_probabilidades_buhos.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tabla_probabilidades_buhos.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tabla_probabilidades_buhos.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tabla_probabilidades_buhos.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tabla_probabilidades_buhos.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tabla_probabilidades_buhos.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tabla_probabilidades_buhos.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tabla_probabilidades_buhos.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tabla_probabilidades_buhos.setItem(2, 2, item)
        self.tabla_probabilidades_buhos.horizontalHeader().setVisible(False)
        self.tabla_probabilidades_buhos.horizontalHeader().setCascadingSectionResizes(False)
        self.tabla_probabilidades_buhos.horizontalHeader().setDefaultSectionSize(500)
        self.tabla_probabilidades_buhos.horizontalHeader().setHighlightSections(True)
        self.tabla_probabilidades_buhos.horizontalHeader().setMinimumSectionSize(40)
        self.tabla_probabilidades_buhos.horizontalHeader().setSortIndicatorShown(True)
        self.tabla_probabilidades_buhos.horizontalHeader().setStretchLastSection(True)
        self.tabla_probabilidades_buhos.verticalHeader().setDefaultSectionSize(100)
        self.tabla_probabilidades_buhos.verticalHeader().setMinimumSectionSize(40)
        self.tabla_probabilidades_buhos.verticalHeader().setSortIndicatorShown(True)
        self.tabla_probabilidades_buhos.verticalHeader().setStretchLastSection(True)
        self.verticalLayout_13.addWidget(self.tabla_probabilidades_buhos)
        self.label_5 = QtWidgets.QLabel(self.frame_13)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_13.addWidget(self.label_5)
        self.tabla_poblacion_buhos = QtWidgets.QTableWidget(self.frame_13)
        self.tabla_poblacion_buhos.setMaximumSize(QtCore.QSize(16777215, 200))
        self.tabla_poblacion_buhos.setObjectName("tabla_poblacion_buhos")
        self.tabla_poblacion_buhos.setColumnCount(3)
        self.tabla_poblacion_buhos.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_poblacion_buhos.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_poblacion_buhos.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_poblacion_buhos.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_poblacion_buhos.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tabla_poblacion_buhos.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tabla_poblacion_buhos.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tabla_poblacion_buhos.setItem(0, 2, item)
        self.tabla_poblacion_buhos.horizontalHeader().setDefaultSectionSize(300)
        self.tabla_poblacion_buhos.verticalHeader().setDefaultSectionSize(30)
        self.tabla_poblacion_buhos.verticalHeader().setMinimumSectionSize(27)
        self.verticalLayout_13.addWidget(self.tabla_poblacion_buhos)
        self.label_6 = QtWidgets.QLabel(self.frame_13)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_13.addWidget(self.label_6)
        self.lineEdit_ingresarAnios = QtWidgets.QLineEdit(self.frame_13)
        self.lineEdit_ingresarAnios.setStyleSheet("font: 50 12pt \"Cascadia SemiBold\";")
        self.lineEdit_ingresarAnios.setPlaceholderText("")
        self.lineEdit_ingresarAnios.setObjectName("lineEdit_ingresarAnios")
        self.verticalLayout_13.addWidget(self.lineEdit_ingresarAnios, 0, QtCore.Qt.AlignLeft)
        self.verticalLayout_13.setStretch(0, 12)
        self.verticalLayout_13.setStretch(1, 112)
        self.verticalLayout_13.setStretch(2, 4)
        self.verticalLayout_13.setStretch(3, 6)
        self.verticalLayout_14.addWidget(self.frame_13)
        self.frame_14 = QtWidgets.QFrame(self.frame_11)
        self.frame_14.setStyleSheet("QPushButton {\n"
"font: 50 12pt \"Cascadia SemiBold\";\n"
"}\n"
"QPushButton:hover{\n"
"border: 20px;\n"
"color: white;\n"
"background-color: gray;\n"
"}\n"
"QPushButton:pressed{\n"
"border: 20px;\n"
"background-color: #ededed;\n"
"}\n"
"")
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_14)
        self.horizontalLayout_12.setContentsMargins(40, -1, 40, -1)
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.btn_probabilidadesRandom = QtWidgets.QPushButton(self.frame_14)
        self.btn_probabilidadesRandom.setObjectName("btn_probabilidadesRandom")
        self.horizontalLayout_12.addWidget(self.btn_probabilidadesRandom)
        self.btn_mostrarGrafica = QtWidgets.QPushButton(self.frame_14)
        self.btn_mostrarGrafica.setObjectName("btn_mostrarGrafica")
        self.horizontalLayout_12.addWidget(self.btn_mostrarGrafica)
        self.btn_vaciarTablaBuhosProbablidades = QtWidgets.QPushButton(self.frame_14)
        self.btn_vaciarTablaBuhosProbablidades.setObjectName("btn_vaciarTablaBuhosProbablidades")
        self.horizontalLayout_12.addWidget(self.btn_vaciarTablaBuhosProbablidades)
        self.verticalLayout_14.addWidget(self.frame_14)
        self.verticalLayout_10.addWidget(self.frame_11)
        self.verticalLayout_10.setStretch(0, 1)
        self.verticalLayout_10.setStretch(1, 7)
        self.horizontalLayout_10.addWidget(self.frame_9)
        self.cambiarPagina.addWidget(self.page_4)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.page_2)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.caja_page_2 = QtWidgets.QFrame(self.page_2)
        self.caja_page_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.caja_page_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.caja_page_2.setObjectName("caja_page_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.caja_page_2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_3 = QtWidgets.QFrame(self.caja_page_2)
        self.frame_3.setStyleSheet("background-color: #93ba5f\n"
"")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_2 = QtWidgets.QFrame(self.frame_3)
        self.frame_2.setStyleSheet("QLabel{\n"
"color: white;\n"
"font: 50 12pt \"Cascadia SemiBold\";\n"
"}\n"
"QComboBox{\n"
"background-color: white;\n"
"font: 50 12pt \"Cascadia SemiBold\";\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    background-color: white;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_comboBox = QtWidgets.QLabel(self.frame_2)
        self.label_comboBox.setStyleSheet("font: 50 12pt \"Cascadia SemiBold\";")
        self.label_comboBox.setObjectName("label_comboBox")
        self.verticalLayout_5.addWidget(self.label_comboBox)
        self.input_nxn_matriz = QtWidgets.QComboBox(self.frame_2)
        self.input_nxn_matriz.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input_nxn_matriz.sizePolicy().hasHeightForWidth())
        self.input_nxn_matriz.setSizePolicy(sizePolicy)
        self.input_nxn_matriz.setMinimumSize(QtCore.QSize(0, 0))
        self.input_nxn_matriz.setMaximumSize(QtCore.QSize(140, 30))
        self.input_nxn_matriz.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.input_nxn_matriz.setInsertPolicy(QtWidgets.QComboBox.InsertAtBottom)
        self.input_nxn_matriz.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.input_nxn_matriz.setPlaceholderText("")
        self.input_nxn_matriz.setFrame(False)
        self.input_nxn_matriz.setObjectName("input_nxn_matriz")
        self.input_nxn_matriz.addItem("")
        self.input_nxn_matriz.addItem("")
        self.input_nxn_matriz.addItem("")
        self.input_nxn_matriz.addItem("")
        self.input_nxn_matriz.addItem("")
        self.input_nxn_matriz.addItem("")
        self.verticalLayout_5.addWidget(self.input_nxn_matriz)
        self.verticalLayout_6.addWidget(self.frame_2)
        self.verticalLayout_4.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.caja_page_2)
        self.frame_4.setStyleSheet("background-color: white;\n"
"")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.frame_5 = QtWidgets.QFrame(self.frame_4)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label = QtWidgets.QLabel(self.frame_5)
        self.label.setStyleSheet("QLabel{\n"
"font: 50 12pt \"Cascadia SemiBold\";\n"
"}")
        self.label.setObjectName("label")
        self.verticalLayout_8.addWidget(self.label, 0, QtCore.Qt.AlignHCenter)
        self.matriz_input = QtWidgets.QTableWidget(self.frame_5)
        self.matriz_input.setEnabled(True)
        self.matriz_input.setMinimumSize(QtCore.QSize(330, 460))
        self.matriz_input.setMaximumSize(QtCore.QSize(16777215, 320))
        self.matriz_input.setAcceptDrops(False)
        self.matriz_input.setStyleSheet("QTableView {\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QTableView QTableCornerButton::section,\n"
"QHeaderView::section {\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QTableView::item {\n"
"    background-color: white;\n"
"    font: 50 12pt \"Cascadia SemiBold\";\n"
"}")
        self.matriz_input.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.matriz_input.setAlternatingRowColors(False)
        self.matriz_input.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.matriz_input.setCornerButtonEnabled(True)
        self.matriz_input.setRowCount(0)
        self.matriz_input.setObjectName("matriz_input")
        self.matriz_input.setColumnCount(0)
        self.matriz_input.horizontalHeader().setVisible(False)
        self.matriz_input.horizontalHeader().setCascadingSectionResizes(False)
        self.matriz_input.horizontalHeader().setHighlightSections(False)
        self.matriz_input.verticalHeader().setVisible(False)
        self.matriz_input.verticalHeader().setHighlightSections(False)
        self.verticalLayout_8.addWidget(self.matriz_input)
        self.frame_7 = QtWidgets.QFrame(self.frame_5)
        self.frame_7.setStyleSheet("QPushButton{\n"
"font: 50 12pt \"Cascadia SemiBold\";\n"
"color: white;\n"
"background-color: rgb(147, 186, 95);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"font: 50 12pt \"Cascadia SemiBold\";\n"
"color: black;\n"
"background-color: white;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"font: 50 12pt \"Cascadia SemiBold\";\n"
"color: white;\n"
"background-color: #dadada;\n"
"}")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem3)
        self.calcular_vectores_propios = QtWidgets.QPushButton(self.frame_7)
        self.calcular_vectores_propios.setObjectName("calcular_vectores_propios")
        self.horizontalLayout_8.addWidget(self.calcular_vectores_propios)
        self.limpiarTabla = QtWidgets.QPushButton(self.frame_7)
        self.limpiarTabla.setObjectName("limpiarTabla")
        self.horizontalLayout_8.addWidget(self.limpiarTabla)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem4)
        self.verticalLayout_8.addWidget(self.frame_7)
        self.verticalLayout_8.setStretch(1, 6)
        self.horizontalLayout_7.addWidget(self.frame_5)
        self.frame_6 = QtWidgets.QFrame(self.frame_4)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_2 = QtWidgets.QLabel(self.frame_6)
        self.label_2.setStyleSheet("QLabel{\n"
"font: 50 12pt \"Cascadia SemiBold\";\n"
"}")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_7.addWidget(self.label_2, 0, QtCore.Qt.AlignHCenter)
        self.lista_resultados = QtWidgets.QListWidget(self.frame_6)
        self.lista_resultados.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lista_resultados.setStyleSheet("QListWidget {\n"
"    font-family: Cascadia SemiBold;\n"
"    font-size: 30px;\n"
"    color: black;\n"
"}\n"
"\n"
"QListWidget::item {\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QListWidget::item:selected {\n"
"    background-color: #ccc;\n"
"}\n"
"\n"
"QListWidget::item:hover {\n"
"    background-color: #ddd;\n"
"}\n"
"\n"
"QListWidget::item:selected:active {\n"
"    background-color: #aaa;\n"
"}\n"
"\n"
"QListWidget::item:selected:!active {\n"
"    color: white;\n"
"}")
        self.lista_resultados.setObjectName("lista_resultados")
        self.verticalLayout_7.addWidget(self.lista_resultados)
        self.verticalLayout_7.setStretch(0, 1)
        self.verticalLayout_7.setStretch(1, 3)
        self.horizontalLayout_7.addWidget(self.frame_6)
        self.horizontalLayout_7.setStretch(0, 1)
        self.horizontalLayout_7.setStretch(1, 1)
        self.verticalLayout_4.addWidget(self.frame_4)
        self.verticalLayout_4.setStretch(0, 1)
        self.verticalLayout_4.setStretch(1, 3)
        self.horizontalLayout_6.addWidget(self.caja_page_2)
        self.cambiarPagina.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.page_3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.cambiarPagina.addWidget(self.page_3)
        self.horizontalLayout_3.addWidget(self.cambiarPagina)
        self.horizontalLayout_2.addWidget(self.contenedor)
        self.verticalLayout.addWidget(self.inferior)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 10)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.cambiarPagina.setCurrentIndex(0)
        self.input_nxn_matriz.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_menu.setText(_translate("MainWindow", "    MENU"))
        self.btn_inicio.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.btn_inicio.setText(_translate("MainWindow", "  Inicio"))
        self.btn_calculadora.setText(_translate("MainWindow", " Calculadora"))
        self.btn_sistema_dinamico.setText(_translate("MainWindow", " Sistema Dinamico"))
        self.frame.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\">Hola</p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "Valores y Vectores propios"))
        self.label_4.setText(_translate("MainWindow", "por Mauricio Marentes Nuñez"))
        self.enlace.setToolTip(_translate("MainWindow", "<html><head/><body><p><a href=\"https://www.pearsonenespanol.com/docs/librariesprovider5/2018-college-open-resources/lay-por-competencias/lay-por-competencias-capitulo-07.pdf?sfvrsn=b634fbb2\"><span style=\" text-decoration: underline; color: white;\">Referencia del sistema dinamico de R. Lamberson y sus ayudantes</span></a></p></body></html>"))
        self.enlace.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial Black\'; font-size:12pt; font-weight:80; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"https://www.pearsonenespanol.com/docs/librariesprovider5/2018-college-open-resources/lay-por-competencias/lay-por-competencias-capitulo-07.pdf?sfvrsn=b634fb\"><span style=\" text-decoration: underline; color:#ffffff;\">Fuente del modelo de Lamberson</span></a></p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "Ingrese las probalidades en la matriz transformación"))
        item = self.tabla_probabilidades_buhos.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Juvenil"))
        item = self.tabla_probabilidades_buhos.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Sub-Adulta"))
        item = self.tabla_probabilidades_buhos.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "Adulta"))
        item = self.tabla_probabilidades_buhos.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "% de que la hembra se convierta en una sub-adulta"))
        item = self.tabla_probabilidades_buhos.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "% de que la hembra se convierta en una adulta"))
        item = self.tabla_probabilidades_buhos.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "% de que la hembra permanezca en etapa juvenil"))
        __sortingEnabled = self.tabla_probabilidades_buhos.isSortingEnabled()
        self.tabla_probabilidades_buhos.setSortingEnabled(False)
        item = self.tabla_probabilidades_buhos.item(0, 0)
        item.setText(_translate("MainWindow", "0"))
        item = self.tabla_probabilidades_buhos.item(0, 1)
        item.setText(_translate("MainWindow", "0"))
        item = self.tabla_probabilidades_buhos.item(0, 2)
        item.setText(_translate("MainWindow", "0"))
        item = self.tabla_probabilidades_buhos.item(1, 0)
        item.setText(_translate("MainWindow", "0"))
        item = self.tabla_probabilidades_buhos.item(1, 1)
        item.setText(_translate("MainWindow", "0"))
        item = self.tabla_probabilidades_buhos.item(1, 2)
        item.setText(_translate("MainWindow", "0"))
        item = self.tabla_probabilidades_buhos.item(2, 0)
        item.setText(_translate("MainWindow", "0"))
        item = self.tabla_probabilidades_buhos.item(2, 1)
        item.setText(_translate("MainWindow", "0"))
        item = self.tabla_probabilidades_buhos.item(2, 2)
        item.setText(_translate("MainWindow", "0"))
        self.tabla_probabilidades_buhos.setSortingEnabled(__sortingEnabled)
        self.label_5.setText(_translate("MainWindow", "Ingrese la poblacion de cada etapa del buho hembra"))
        item = self.tabla_poblacion_buhos.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Numero de población"))
        item = self.tabla_poblacion_buhos.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Juvenil"))
        item = self.tabla_poblacion_buhos.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Sub-Adulto"))
        item = self.tabla_poblacion_buhos.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Adulto"))
        __sortingEnabled = self.tabla_poblacion_buhos.isSortingEnabled()
        self.tabla_poblacion_buhos.setSortingEnabled(False)
        item = self.tabla_poblacion_buhos.item(0, 0)
        item.setText(_translate("MainWindow", "0"))
        item = self.tabla_poblacion_buhos.item(0, 1)
        item.setText(_translate("MainWindow", "0"))
        item = self.tabla_poblacion_buhos.item(0, 2)
        item.setText(_translate("MainWindow", "0"))
        self.tabla_poblacion_buhos.setSortingEnabled(__sortingEnabled)
        self.label_6.setText(_translate("MainWindow", "Ingrese la cantidad de años para visualizarlo en la grafica"))
        self.btn_probabilidadesRandom.setText(_translate("MainWindow", "generar probalidades aleatorias"))
        self.btn_mostrarGrafica.setText(_translate("MainWindow", "Mostrar Grafica del sistema dinamico"))
        self.btn_vaciarTablaBuhosProbablidades.setText(_translate("MainWindow", "Vaciar tabla probabilidades"))
        self.label_comboBox.setText(_translate("MainWindow", "Seleccione un formato de matriz cuadrada"))
        self.input_nxn_matriz.setItemText(0, _translate("MainWindow", "1x1"))
        self.input_nxn_matriz.setItemText(1, _translate("MainWindow", "2x2"))
        self.input_nxn_matriz.setItemText(2, _translate("MainWindow", "3x3"))
        self.input_nxn_matriz.setItemText(3, _translate("MainWindow", "4x4"))
        self.input_nxn_matriz.setItemText(4, _translate("MainWindow", "5x5"))
        self.input_nxn_matriz.setItemText(5, _translate("MainWindow", "6x6"))
        self.label.setText(_translate("MainWindow", "Ingrese valores para la matriz"))
        self.calcular_vectores_propios.setText(_translate("MainWindow", "Calcular vectores propios"))
        self.limpiarTabla.setText(_translate("MainWindow", "Limpiar tabla y resultados"))
        self.label_2.setText(_translate("MainWindow", "Resultado"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
